######### Cadastro Tópico 
POST http://127.0.0.1:3333/topics HTTP/1.1 
Content-Type: application/json 
Authorization: Bearer NA.Yew4dG8Xrqme0_CycdUExLl11lSIAf9GVeK64E3P0TvLhiNZlMGKahEPXQqp

{
"name": "Recomendações"
}

######### Listar todos os Tópico 
GET http://127.0.0.1:3333/topics HTTP/1.1 
Content-Type: application/json 
Authorization: Bearer NA.Yew4dG8Xrqme0_CycdUExLl11lSIAf9GVeK64E3P0TvLhiNZlMGKahEPXQqp

######### Listar Tópico específico 
GET http://127.0.0.1:3333/topics/1 HTTP/1.1 
Content-Type: application/json 
Authorization: Bearer NA.Yew4dG8Xrqme0_CycdUExLl11lSIAf9GVeK64E3P0TvLhiNZlMGKahEPXQqp

######### Alterar Tópico 
PUT http://127.0.0.1:3333/topics/1 HTTP/1.1 
Content-Type: application/json 
Authorization: Bearer NA.Yew4dG8Xrqme0_CycdUExLl11lSIAf9GVeK64E3P0TvLhiNZlMGKahEPXQqp

{
"name": "Web II"
}

######### Apagar Tópico 
DELETE http://127.0.0.1:3333/topics/1 HTTP/1.1 
Content-Type: application/json 
Authorization: Bearer NA.Yew4dG8Xrqme0_CycdUExLl11lSIAf9GVeK64E3P0TvLhiNZlMGKahEPXQqp