######### Cadastro Tópico 
POST http://127.0.0.1:3333/topics HTTP/1.1 
Content-Type: application/json 
Authorization: Bearer Mg.ieN2eT_CUuNsUb4i8zR1owdIYtmnRmh5RIWeryGU9F_PlaCPwBUEq874saO6

{
"name": "Recomendações"
}

######### Listar todos os Tópico 
GET http://127.0.0.1:3333/topics HTTP/1.1 
Content-Type: application/json 
Authorization: Bearer Mg.ieN2eT_CUuNsUb4i8zR1owdIYtmnRmh5RIWeryGU9F_PlaCPwBUEq874saO6

######### Listar Tópico específico 
GET http://127.0.0.1:3333/topics/1 HTTP/1.1 
Content-Type: application/json 
Authorization: Bearer Mg.ieN2eT_CUuNsUb4i8zR1owdIYtmnRmh5RIWeryGU9F_PlaCPwBUEq874saO6

######### Alterar Tópico 
PUT http://127.0.0.1:3333/topics/1 HTTP/1.1 
Content-Type: application/json 
Authorization: Bearer Mg.ieN2eT_CUuNsUb4i8zR1owdIYtmnRmh5RIWeryGU9F_PlaCPwBUEq874saO6

{
"name": "Web II"
}

######### Apagar Tópico 
DELETE http://127.0.0.1:3333/topics/1 HTTP/1.1 
Content-Type: application/json 
Authorization: Bearer Mg.ieN2eT_CUuNsUb4i8zR1owdIYtmnRmh5RIWeryGU9F_PlaCPwBUEq874saO6